import { bindRepository } from "./repository-factory.ts";
import type { RepositoryTransactionLifetime } from "./transaction.ts";
import type { PlatformUnitOfWork } from "../state/platform-state.ts";

/** The explicit outward projection shares one transaction lifetime. */
export function bindPlatformUnitOfWork(
  repositories: PlatformUnitOfWork,
  lifetime: RepositoryTransactionLifetime,
): PlatformUnitOfWork {
  return Object.freeze({
    installations: bindRepository(repositories.installations, lifetime, [
      "findInstallation",
      "getInstallation",
      "createInstallation",
      "holdPrincipalAccount",
    ]),
    namespaces: bindRepository(repositories.namespaces, lifetime, [
      "findNamespace",
      "listNamespaces",
      "createNamespace",
      "lockNamespace",
      "hasAgents",
      "hasConfigurations",
      "listConfigurationIds",
      "hasPresets",
      "hasServiceAccounts",
      "hasSecrets",
      "hasCredentialSources",
      "transitionNamespaceStatus",
      "markNamespaceDeleted",
    ]),
    configurations: bindRepository(repositories.configurations, lifetime, [
      "findConfiguration",
      "createConfiguration",
      "lockConfiguration",
      "advanceConfigurationGeneration",
      "deleteConfiguration",
    ]),
    presets: bindRepository(repositories.presets, lifetime, [
      "findPreset",
      "listPresets",
      "createPreset",
      "lockPreset",
      "updatePreset",
      "deletePreset",
    ]),
    secrets: bindRepository(repositories.secrets, lifetime, [
      "findSecret",
      "listSecrets",
      "listReferences",
      "lockSecret",
      "createSecret",
      "deleteSecret",
      "hasReferences",
    ]),
    credentialSources: bindRepository(repositories.credentialSources, lifetime, [
      "findCredentialSource",
      "listCredentialSources",
      "lockCredentialSource",
      "createCredentialSource",
      "markCredentialSourceDeleting",
      "markCredentialSourceReady",
      "replaceCredentialSourceSecrets",
      "deleteCredentialSource",
      "hasReferences",
      "findBlockingReference",
      "findCredentialWithdrawal",
      "listCredentialWithdrawals",
      "requestCredentialWithdrawal",
      "reassignCredentialWithdrawal",
      "recordCredentialWithdrawalAttempt",
      "markCredentialWithdrawalRevoked",
    ]),
    serviceAccounts: bindRepository(repositories.serviceAccounts, lifetime, [
      "findServiceAccount",
      "listServiceAccounts",
      "findServiceAccountBackendBinding",
      "createServiceAccount",
      "lockServiceAccount",
      "updateCredential",
      "deleteServiceAccount",
      "hasReferences",
    ]),
    workspaceSetups: bindRepository(repositories.workspaceSetups, lifetime, [
      "find",
      "create",
      "complete",
      "delete",
    ]),
    agents: bindRepository(repositories.agents, lifetime, [
      "findAgentForBrowsing",
      "listAgentsForBrowsing",
      "findAgent",
      "listAgents",
      "createAgent",
      "lockAgent",
      "updateConfiguration",
      "compareAndSetActiveRevision",
      "compareAndClearActiveRevision",
      "transitionAgentDesiredRuntimeState",
      "transitionAgentStatus",
    ]),
    revisions: bindRepository(repositories.revisions, lifetime, [
      "findRevisionForBrowsing",
      "listRevisionsForBrowsing",
      "findRevision",
      "listRevisions",
      "createRevision",
    ]),
    iamPolicy: bindRepository(repositories.iamPolicy, lifetime, [
      "listRoles",
      "getRole",
      "createRole",
      "deleteRole",
      "listAccessBindings",
      "getAccessBinding",
      "listRestrictionsTargeting",
      "createAccessBinding",
      "updateRuntimeRole",
      "deleteAccessBinding",
      "listServicePrincipals",
      "getServicePrincipal",
      "createServicePrincipal",
    ]),
    repositorySessions: bindRepository(repositories.repositorySessions, lifetime, [
      "findAttempt",
      "findBrokerReceipt",
      "findBrokerReceiptBySession",
      "listRevisionAttempts",
      "listNamespaceAttempts",
      "createAttempt",
      "advanceAttempt",
      "lockAttempt",
      "createBrokerReceipt",
      "advanceBrokerReceipt",
      "fenceBrokerReceipt",
    ]),
    provisioning: bindRepository(repositories.provisioning, lifetime, [
      "findByWorkId",
      "findWithWork",
      "hasPendingNamespaceProvisioning",
      "findByAgent",
      "findByConfiguration",
      "findByRequest",
      "create",
      "beginEffect",
      "checkpoint",
      "recordFailure",
      "settleEffect",
      "cancel",
      "cancelByAgent",
      "retryByWorkId",
      "releaseConfiguration",
    ]),
    audit: bindRepository(repositories.audit, lifetime, ["append", "list"]),
    operations: bindRepository(repositories.operations, lifetime, [
      "append",
      "list",
      "findWork",
      "findWorkAttempt",
      "hasOutstandingCredentialWithdrawalWork",
      "retryFailedAgentDeletion",
      "retryFailedNamespaceDeletion",
      "expediteCredentialWithdrawalWork",
    ]),
  });
}
